### ISSUE TITLE
Attempting to get image for background & banner... Couldn't find any images for: 5   Smart Boy

### ISSUE THREAD

**Issue by Ilikeas64** [phr00t/AutoStepper#25]
hi, for some reason autostepper can't find any images for background & banner as seen in the title. also the metadata is empty.

**Comment by dreammare64** [comment]
so true, i tried another versions or clean reinstalls. but that never solves the problem, the background & banners never appear. and the metadata always get empty.

**Comment by dreammare64** [comment]
if you get any solutions, please give us right now.

**Comment by phr00t** [comment]
This tool was developed years ago and used methods for gathering images that have long become outdated as service providers changed. I do not maintain this repository anymore. Ultimately someone needs to rewrite searching and downloading pictures based on the filename of the audio file.
