### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by JamieMagee** [phr00t/AutoStepper#6]
It is rather unusual for a software project to be licensed under a Creative Commons license. CC licenses are intended for creative material (writing, art, music, etc.). Normally software uses a license like [MIT](https://choosealicense.com/licenses/mit/) or [Apache](https://choosealicense.com/licenses/apache-2.0/).

Creative Commons even [advises against using their licenses for software](https://choosealicense.com/licenses/apache-2.0/)

Github [has a help page](https://help.github.com/articles/adding-a-license-to-a-repository/) about how to add a new license to a project.

**Comment by phr00t** [comment]
Those other licenses allow for commercial use, which I'm not ready to provide at this moment.

**Comment by JamieMagee** [comment]
Thanks for the reply. I just realised that I attached the wrong link to the Creative Commons website. It was supposed to be [this page](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

I can totally understand if you don't want to relicense. So I'd like to ask your special permission to use/modify AutoStepper for a hackathon project 🙂 Of course, you would still retain the license and copyright to all the code you've written. 

I plan to use AutoStepper and [youtube-dl](https://github.com/rg3/youtube-dl) to make it easy to generate StepMania `*.sm` files. It's a fun mini-project for me and some friends, but I would like open source the project afterwards, to contribute back to the StepMania community. Would I have your permission to do this?

Please let me know if you have any more questions about the project!

All the best,

Jamie

**Comment by phr00t** [comment]
I couldn't find a license readily available that restricted commercial use, so I modified the MIT license to restrict commercial use & require attribution. See https://github.com/phr00t/AutoStepper/blob/master/README.md for the new license.

**Comment by JamieMagee** [comment]
Thanks for relicensing. The MIT license is a lot easier to work with. I'll let you know what we come up with during the hackathon!
