### ISSUE TITLE
Provide an easy way to build from sources

### ISSUE THREAD

**Issue by yac** [phr00t/AutoStepper#7]
This is discussed in https://github.com/phr00t/AutoStepper/pull/1

Making each potential contributor set up his/hers IDE/build system is a huge block. Please integrate build system of your choice into the source repository.

My reccommendation would be gradle which I already tested thanks to https://github.com/JamieMagee/AutoStepper/commit/cc8c9572fc65006662a1e119f7b550623f8658d2 as disccussed in in https://github.com/phr00t/AutoStepper/pull/1 . Anything that works with one terminal command is fine, really - you're the boss here.

**Comment by phr00t** [comment]
JamieMagee already forked the project & made it into a gradle project. There is another fork that mavenized the project. I don't use either for AutoStepper, so I haven't been planning on changing this project structure.
